version: '2'
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: jupiter
      MYSQL_USER: rootdb
      MYSQL_ROOT_PASSWORD: rootdb
