version: '2'
services:
  postgres:
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: jupiter
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
